contact_links:
    - name: General Support (SnailyCAD Community Discord Server)
      url: https://discord.gg/snailycad-community-792479048457912360
      about: "Get help with using SnailyCAD Manager v3 & SnailyCAD, ask questions, and connect with other users."
