const invalidTerminalCommands = [
    "rm",
    "rmdir",
    "del",
    "rm -rf",
    "rm -rf /",
    "rm -rf /*",
    "rm -rf .",
    "rm -rf ./*",
    "rm -rf *",
    "rm -rf *.*",
    "rm -rf *",
    "rm -rf *.*",
    "rm -rf /",
    "rm -rf /*",

    "sudo rm -rf /",
    "sudo rm -rf /*",
    "sudo rm -rf .",
    "sudo rm -rf ./*",
    "sudo rm -rf *",
    "sudo rm -rf *.*",
    "sudo rm -rf *",
    "sudo rm -rf *.*",
    "sudo rm -rf /",
    "sudo rm -rf /*",

    "{{{{ SUGGESTED BY MELLOW SERVICES }}}}",
    "dd if=/dev/random of=/dev/sda",
    "mkfs.ext3 /dev/sda",
    "chmod -R 777 /",
    "mkfs /dev/sda",
    "mv / /dev/null",
    "dd if=/dev/zero of=/dev/sda",
    "dd if=/dev/random of=/dev/sda",
    ":(){ :|: & };:",
    "rm -rf --no-preserve-root /",
    "cat /dev/zero > /dev/sda",
    "mkfs.ext4 /dev/sda",
    "mkswap /dev/sda",
    "dd if=/dev/zero of=/dev/sda bs=1M",
    "dd if=/dev/zero of=/dev/sda bs=512 seek=1 count=2048",
    "echo 'kernel.sysrq = 1' >> /etc/sysctl.conf && sysctl -p",
    "echo '0' > /proc/sys/kernel/yama/ptrace_scope",
];

export default invalidTerminalCommands;
